language: node_js
node_js:
  - 10.16.3
services:
  - mysql
before_install:
  - mysql -u root --password="" < db/create_test_db.sql
install:
  - npm install
  - npm run make-src
  - npm run make-test
script:
  - npm run i-tests-travis