/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetWorldResponse {
  world: World;
}
export interface World {
  id: number;
  map: Map;
  cities: any[];
  marches: any[];
}
export interface Map {
  tiles: any[];
}
