/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Message {
  service: string;
  operation: string;
  data: {
    [k: string]: any;
  };
  user?: User;
  token?: JWT;
}
export interface User {
  userID: number;
  username: string;
}
export interface JWT {
  value: string;
}
