version: '3'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - my-datavolume:/var/lib/mysql
  world:
    build:
      dockerfile: ./dockerfiles/Dockerfile
      context: ../
    depends_on:
      - "db"
    environment:
      DB_HOSTNAME: db
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: master
    ports:
      - "1337:1337"
volumes:
  my-datavolume:
