export enum ServiceOperations {
  CreatePlayer = 'createPlayer',
  CreatePlayerError = 'createPlayerError',
  CreateMarch = 'createMarch',
  CreateMarchError = 'createMarchError',
  GetCities = 'getCities',
  GetCitiesError = 'getCitiesError',
  GetMyPlayers = 'getMyPlayers',
  GetMyPlayersError = 'getMyPlayersError',
  GetWorld = 'getWorld',
  GetWorldError = 'getWorldError',
  LoginUser = 'loginUser',
  LoginUserError = 'loginUserError',
  RegisterUser = 'registerUser',
  RegisterUserError = 'registerUserError',
}
